---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Allow SSH, HTTP, and HTTPS through firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Ensure UFW is enabled and running
  ufw:
    state: enabled
    default: deny

- name: Reload UFW to apply changes
  ufw:
    state: reloaded

- name: Download image
  get_url:
    url: https://github.com/wineperm/Diplom-yc/blob/main/APP/html/KLS_netology_12.07.2004.jpeg?raw=true
    dest: /usr/share/nginx/html/KLS_netology_12.07.2004.jpeg

- name: Customize default Nginx page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Update Nginx configuration
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;

          root /usr/share/nginx/html;

          index index.html index.htm index.nginx-debian.html;

          server_name _;

          location / {
              try_files $uri $uri/ =404;
          }
      }

- name: Restart Nginx service
  service:
    name: nginx
    state: restarted
