name: Deploy Nginx

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p /tmp
        echo "$SSH_PRIVATE_KEY" > /tmp/ansible_ssh_private_key
        chmod 600 /tmp/ansible_ssh_private_key

    - name: Run Ansible playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
      run: |
        ansible-playbook -i inventory/hosts.ini ansible/site.yml
