name: Build and Deploy Docker Container

on:
  push:
    paths:
      - 'ansible/roles/nginx/templates/index.html.j2'
  workflow_dispatch:

jobs:
  build-and-push:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        push: true
        tags: wineperm/nginx-custom:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run Ansible playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
        ANSIBLE_SSH_PRIVATE_KEY_FILE: ~/.ssh/id_rsa
      run: |
        ansible-playbook -i inventory/hosts.ini ansible/site.yml
