name: Build and Deploy Docker Container

on:
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check-changes.outputs.changes }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 2

    - name: Check for changes in index.html.j2
      id: check-changes
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q 'ansible/roles/nginx/templates/index.html.j2'; then
          echo "changes=true" >> $GITHUB_ENV
        else
          echo "changes=false" >> $GITHUB_ENV
        fi

  build-and-push:
    needs: check-changes
    if: needs.check-changes.outputs.changes == 'true'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        push: true
        tags: wineperm/nginx-ansible:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run Ansible playbook for Nginx Docker
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
        ANSIBLE_SSH_PRIVATE_KEY_FILE: ~/.ssh/id_rsa
      run: |
        ansible-playbook -i inventory/hosts.ini ansible/site.yml --tags nginx-docker
